In [2]:
import numpy as np


Numpy Arrays

In [3]:
V= np.array([ 65,1,56])

In [4]:
V


array([65,  1, 56])

In [5]:
c= [(0.1,0.2,0.5)]


In [6]:
c

[(0.1, 0.2, 0.5)]

In [7]:
B = V * c

In [8]:
B

array([[ 6.5,  0.2, 28. ]])

In [9]:
Data=np.array([[65,1,56],
               [45,4,64],
               [78,4,59],
               [56,3,34],
               [79,2,36]])

In [10]:
Data.shape

(5, 3)

In [11]:
Data.dtype


dtype('int32')

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones([2,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(6)

array([0.98096337, 0.59863086, 0.79360263, 0.47330285, 0.68393305,
       0.46965034])

In [17]:
np.random.randn(2,4)

array([[ 0.11677497, -1.03562117,  1.23034785, -1.30363789],
       [ 0.04717998, -0.89732875,  0.18903808,  2.9285629 ]])

In [18]:
np.arange(5, 45, 8)

array([ 5, 13, 21, 29, 37])

In [20]:
np.full([3,2],66)

array([[66, 66],
       [66, 66],
       [66, 66]])

In [22]:
np.linspace(5, 20 ,12)

array([ 5.        ,  6.36363636,  7.72727273,  9.09090909, 10.45454545,
       11.81818182, 13.18181818, 14.54545455, 15.90909091, 17.27272727,
       18.63636364, 20.        ])

In [26]:
x=np.array([10,20,30])

In [27]:
x

array([10, 20, 30])

In [28]:
x.ndim

1

In [29]:
x.itemsize

4

In [30]:
x.dtype

dtype('int32')

In [31]:
y=( [ 3,5],[4,6],[8,9])

In [32]:
y

([3, 5], [4, 6], [8, 9])

dtype=complex

In [37]:
y=np.array([[3,5],[4,6],[8,9]],dtype=np.float64)

In [38]:
y

array([[3., 5.],
       [4., 6.],
       [8., 9.]])

In [39]:
y.shape

(3, 2)

In [40]:
y.reshape(2,3)

array([[3., 5., 4.],
       [6., 8., 9.]])

ravel- flattens array into one dimesional array,it returns a new array

In [41]:
y.ravel()


array([3., 5., 4., 6., 8., 9.])

In [42]:
y

array([[3., 5.],
       [4., 6.],
       [8., 9.]])

In [46]:
y.min()

3.0

In [47]:
y.max()

9.0

In [49]:
y.sum()

35.0

Column wise sum:axis=0

In [50]:
y.sum(axis=0)

array([15., 20.])

Row wise sum:axis=1

In [51]:
y.sum(axis=1)

array([ 8., 10., 17.])

Find the squareroot of each element in the array

In [52]:
np.sqrt(y)

array([[1.73205081, 2.23606798],
       [2.        , 2.44948974],
       [2.82842712, 3.        ]])

Cosider two 2D arrays

In [53]:
c= np.array( [[2,4], [6,7]])

In [54]:
d=np.array( [[1,1], [1,1]])

In [55]:
c+d

array([[3, 5],
       [7, 8]])

In [56]:
c-d

array([[1, 3],
       [5, 6]])

In [57]:
c*d

array([[2, 4],
       [6, 7]])

Indexing /Slicing 

In [58]:
t= [9,3,5]

In [61]:
t[0:2]

[9, 3]

In [62]:
t[-1]

5

Multi Dimensional Array

In [64]:
z= np.array ([[4,6,9],[3,6,2],[2,7,9]])

In [65]:
z

array([[4, 6, 9],
       [3, 6, 2],
       [2, 7, 9]])

In [69]:
z[2,2]

9

In [68]:
z [2,1]

7

In [71]:
for row in z:
 print(row)

[4 6 9]
[3 6 2]
[2 7 9]


Stacking two arrays

In [72]:
a = np.arange(9).reshape(3,3)

In [73]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
b = np.arange(9,18).reshape(3,3)

In [80]:
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [81]:
np.vstack((a,b))

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [82]:
np.hstack((a,b))

array([[ 9, 10, 11,  9, 10, 11],
       [12, 13, 14, 12, 13, 14],
       [15, 16, 17, 15, 16, 17]])

In [89]:
h=np.arange(30).reshape(2,15)

In [87]:
h

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
Splitting the array into smaller arrays

In [91]:
np.hsplit(h,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [93]:
d=np.vsplit(h,2)

In [94]:
d[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [95]:
d[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [97]:
s = np.arange(12).reshape(3,4)


In [98]:
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
c = s>4

In [100]:
c

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

Solving System of Linear Equations - If we consider the equations 2.0x1+4.0x2=4, 2.0x1+1.0x2=6

In [101]:
X = np.array([
        [2., 4.],
        [2., 1.]], dtype=np.dtype(int))

y = np.array([4., 6.], dtype=np.dtype(int))


In [102]:
X

array([[2, 4],
       [2, 1]])

In [103]:
y

array([4, 6])

In [105]:
X.shape

(2, 2)

In [106]:
y.shape

(2,)

In [107]:
z=np.linalg.solve(X,y)

In [108]:
z

array([ 3.33333333, -0.66666667])

In [112]:
q=np.linalg.det(X)

In [113]:
q

-6.0

The result is a non zero value that means this system has only one solution.

Multiplying Vector with a Scalar 

In [114]:
vec = np.array([2, 3])
vec * 2.6

array([5.2, 7.8])

Matrix Multiplication

In [115]:
np.matmul(a, b)

array([[366, 396, 426],
       [474, 513, 552],
       [582, 630, 678]])

In [116]:
a @ b

array([[366, 396, 426],
       [474, 513, 552],
       [582, 630, 678]])

In [119]:
a1=np.array([[4,3,4],[8,3,2],[3,2,7]])
b1=np.array([[3,2],[2,1],[8,9]])

In [ ]:
Outputs a 3x 2 matrix;With matrix multiplication it is important that
the number of the columns in the first matrix should match the number of the rows in the second matrix

In [122]:
a1 @ b1

array([[50, 47],
       [46, 37],
       [69, 71]])

In [ ]:
Try b1 @ a1

In [124]:
c1=np.array([4,2,6])
d1=np.array([6,1,3])

In [125]:
c1.shape

(3,)

In [126]:
c1.ndim

1

In [127]:
c1.reshape(3,1).shape


(3, 1)

In [128]:
c1.reshape(3,1).ndim

2

In [129]:
np.matmul(c1,d1)

44

In [130]:
np.dot(c1,d1)

44

In [131]:
c1-4

array([ 0, -2,  2])

In [ ]:
This is called broadcasting,where the subtraction is done element by element 

In [4]:
S = np.array([[3, -2],[-1,4]])
S

array([[ 3, -2],
       [-1,  4]])

In [147]:
K=np.linalg.inv(S)
K

array([[0.4, 0.2],
       [0.1, 0.3]])

In [5]:
Y= ([[1],[3]])
Y

[[1], [3]]

In [151]:
K@Y

array([[1.],
       [1.]])

In [6]:
w= np.linalg.solve(S,Y)

In [7]:
w

array([[1.],
       [1.]])