# Lab1  - Manu Mathew - 8990691

### Part A

#### Adding the necessary imports

In [1]:
import numpy as np

#### 2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
arrayOfIntegers = np.arange(1,21,3)
print("The array of integers that starts from the integer 1, ends at 20 , incremented by 3 is", arrayOfIntegers)

The array of integers that starts from the integer 1, ends at 20 , incremented by 3 is [ 1  4  7 10 13 16 19]


#### 3. Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
arrayOfRandomNumbers = np.random.rand(3)
print("The array of shape 3 of random numbers between 0 and 1 is ",arrayOfRandomNumbers)

The array of shape 3 of random numbers between 0 and 1 is  [0.09691161 0.32894305 0.97429115]


#### 4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:  Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
twoDimentionalArray = np.array([[10,20,45], [30,12,16], [42,17,56]])
print("The 2D array is :\n", twoDimentionalArray)
print("Slicing the array to get the first two rows and the last two rows.")
print("The first two rows are : \n", twoDimentionalArray[:2])
print("The last two rows are : \n", twoDimentionalArray[1:])


The 2D array is :
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
Slicing the array to get the first two rows and the last two rows.
The first two rows are : 
 [[10 20 45]
 [30 12 16]]
The last two rows are : 
 [[30 12 16]
 [42 17 56]]


#### 5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

- Stacking the elements vertically means stacking one array on top of another and stacking the elements horizontally means stacking the array beside one another.

In [5]:

firstTwoCrossTwoArray = np.array([[10,14], [1,2]])
secondTwoCrossTwoArray = np.array([[18,16], [3,4]])
print('The two 2 X 2 arrays are: \n', firstTwoCrossTwoArray, '\n \n', secondTwoCrossTwoArray, '\n')

print('Stacking the elements vertically means placing one array on the top of other. \n')
verticalStackedElements = np.vstack((firstTwoCrossTwoArray,secondTwoCrossTwoArray))
print(verticalStackedElements, '\n')

print('Stacking the elements horizontally means placing one array next to the other. \n')
horizontallyStackedElements = np.hstack((firstTwoCrossTwoArray,secondTwoCrossTwoArray))
print(horizontallyStackedElements, '\n')

print('Splitting the vertically stacked arrays means splitting into two equal halves by row. \n')
verticallySplitElements = np.vsplit(verticalStackedElements,2)
for vArr in verticallySplitElements:
    print(vArr,"\n")


print('Splitting the horizontally stacked arrays means means splitting into two equal halves by column. \n')
horizontallySplitElements = np.hsplit(horizontallyStackedElements,2)
for hArr in horizontallySplitElements:
    print(hArr, "\n")

The two 2 X 2 arrays are: 
 [[10 14]
 [ 1  2]] 
 
 [[18 16]
 [ 3  4]] 

Stacking the elements vertically means placing one array on the top of other. 

[[10 14]
 [ 1  2]
 [18 16]
 [ 3  4]] 

Stacking the elements horizontally means placing one array next to the other. 

[[10 14 18 16]
 [ 1  2  3  4]] 

Splitting the vertically stacked arrays means splitting into two equal halves by row. 

[[10 14]
 [ 1  2]] 

[[18 16]
 [ 3  4]] 

Splitting the horizontally stacked arrays means means splitting into two equal halves by column. 

[[10 14]
 [ 1  2]] 

[[18 16]
 [ 3  4]] 



#### 6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?. Demonstrate the case when it is not possible to.

- Yes it is possible to muliply because the number of columns in matrix x is qual to number of rows in y. To demonstrate where the matrix multiplication is not possible, let us take two examples of matrices where matrix a =  [[5 7 2]
 [4 5 6]]  and b =   [[4 2]
 [6 2]]  and the error encoutered there is shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0) and this is " \
"because the number of columns in matrix a is not equal to number of rows in matrix b. Commenting the line below for successful execution of all cells

In [6]:
x = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
y = np.array([[4, 2], [6, 2], [4, 2]])
print("Yes it is possible to muliply because the number of columns in matrix x is qual to number of rows in y.")
print("Multiplying matrix x and matrix y :")
finalProduct = np.dot(x,y)
print(finalProduct,"\n")
a = np.array([[5, 7, 2], [4, 5, 6]])
b = np.array([[4, 2], [6, 2]])
print("To demonstrate where the matrix multiplication is not possible, let us take two examples of matrices where matrix a  is \n", a,"\n" , "\n matrix b is \n ", b)
print("We encounter an erro here. The error message is shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0) and this is " \
"because the number of columns in matrix a is not equal to number of rows in matrix b. Commenting the line below for successful execution of all cells")
# matMultiplication = np.dot(a,b)


Yes it is possible to muliply because the number of columns in matrix x is qual to number of rows in y.
Multiplying matrix x and matrix y :
[[70 28]
 [70 30]
 [60 26]] 

To demonstrate where the matrix multiplication is not possible, let us take two examples of matrices where matrix a  is 
 [[5 7 2]
 [4 5 6]] 
 
 matrix b is 
  [[4 2]
 [6 2]]
We encounter an erro here. The error message is shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0) and this is because the number of columns in matrix a is not equal to number of rows in matrix b. Commenting the line below for successful execution of all cells


####   7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [7]:
x = np.array([2,-1,-8])
y = np.array([3,1,-2])

print("Shape of vector x")
print(x.shape, "\n")

print("Dimensions of vector x")
print(x.ndim,"\n")

print("Reshaping the vector x to a matrix of size (3,1)")
print(x.reshape(3,1), "\n")

print("Reshaping the vector y to a matrix of (3,1)")
print(y.reshape(3,1))


Shape of vector x
(3,) 

Dimensions of vector x
1 

Reshaping the vector x to a matrix of size (3,1)
[[ 2]
 [-1]
 [-8]] 

Reshaping the vector y to a matrix of (3,1)
[[ 3]
 [ 1]
 [-2]]


#### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

- Broadcasting in NumPy helps in arithmetic operations between arrays of different shapes by automatically expands the smaller array to match the shape of the larger one without copying data, provided the shapes are compatible ,if they are equal to or one of them is 1.

In [8]:
m = np.array([[11, 12, 13],
              [14, 15, 16],
              [17,18,19]])

n = np.array([1, 2, 3])

print("The matrices are matrix m \n", m,"\n and the matrix n \n",n)

print("The product of two matrix are \n", m*n)

print("The difference of two matrix are \n", m-n)


The matrices are matrix m 
 [[11 12 13]
 [14 15 16]
 [17 18 19]] 
 and the matrix n 
 [1 2 3]
The product of two matrix are 
 [[11 24 39]
 [14 30 48]
 [17 36 57]]
The difference of two matrix are 
 [[10 10 10]
 [13 13 13]
 [16 16 16]]


#### 9.  Brief overview of the steps from 1 to 8

In this assignment I, are using the numpy library and so I have imported the numpy library and then according to challenge two I created an array that starts with integer 1 and ends at 20 incremented by 3. And then according to the challenge 3, I created an array of shape 3 with random numbers between 0 and 1. And then in challenge 4, I created a  2D array [[10,20,45], [30,12,16], [42,17,56]] and sliced the 2D array to get the first two rows, slice the 2D array to get the last two rows.And then I created a two 2 X 2 arrays and demonstrated how I can stack the elements horizontally vertically and split the arrays to smaller arrays. And then I created two  matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]) and I multiplied them and also demonstrated the case when the multiplication of matrices are not possible. And then according to the next challenge I created two arrays  x = ([2, -1, -8]) y = ([3, 1, -2]), found the Shape, Number of dimensions of vector x. Reshaped the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1). Finally I have explained how, does the broacasting work and I have demonstrated substraction and multiplication by considering a 3 X 3 matrix.

#### 9. Brief overview on graphs

- Line Plot: Displays trends in data over time or on a continuous scale by connecting different points.

- Scatter Plot: Shows the relaionship between two numerical values in which each dot represents a distinct data point.  

- Bar Chart: Uses bars whose lengths correspond to their values to highlight to highlight changes at particular intervals.

- Histogram: Represents how many values fall into each bin to represent the distribution of a single numerical variable.

### Part B

#### 1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. 2x1+3x2-4x3=6,x1-4x2=8 , 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [9]:
first_Matrix = np.array([[2, 3, -4],
               [1, -4, 0]])
second_Matrix = np.array([6, 8])
x1ForFirstEquations , firstResiduals, firstRank, s = np.linalg.lstsq(first_Matrix, second_Matrix, rcond=None)
aB = np.hstack((first_Matrix, second_Matrix.reshape(-1, 1)))
rank_aB = np.linalg.matrix_rank(aB)

x1, x2, x3 = x1ForFirstEquations
print("The value of x1 is", x1)
print("The value of x2 is", x2)
print("The value of x3 is", x3)
print("Residuals:", firstResiduals)
print("Rank of matrix A:", firstRank)

if firstRank == rank_aB:
    if firstRank < first_Matrix.shape[1]:
        print("Infinite solutions")
    else:
        print("Unique solution")
else:
    print("No solution")

The value of x1 is 1.669211195928752
The value of x2 is -1.5826972010178109
The value of x3 is -1.852417302798981
Residuals: []
Rank of matrix A: 2
Infinite solutions


In [10]:
MatrixA = np.array([[3, -4, 5],
               [-1, 2, -4]])
MatrixB = np.array([10, 8])
x , secResiduals, secRank, s = np.linalg.lstsq(MatrixA, MatrixB, rcond=None)
bC = np.hstack((MatrixA, MatrixB.reshape(-1, 1)))
rank_bC = np.linalg.matrix_rank(bC)

x1, x2, x3 = x
print("The value of x1 is", x1)
print("The value of x2 is", x2)
print("The value of x3 is", x3)
print("Residuals:", secResiduals)
print("Rank of matrix A:", secRank)
if secRank == rank_bC:
    if firstRank < MatrixA.shape[1]:
        print("Infinite solutions")
    else:
        print("Unique solution")
else:
    print("No solution")

The value of x1 is 7.460674157303374
The value of x2 is -4.629213483146074
The value of x3 is -6.179775280898881
Residuals: []
Rank of matrix A: 2
Infinite solutions
